server:
  port: 8060
spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: CARSERVICE
            uri: lb://CARSERVICE
            predicates: 
            - Path=/car/** 
          - id: PERSONSERVICE
            uri: lb://PERSONSERVICE
            predicates: 
            - Path=/person/** 
eureka:
  
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
